### ISSUE TITLE
Several 1D Transform at once with ~many:true

### ISSUE THREAD

**Issue by h2o64** [Chris00/fftw-ocaml#11]
Hi,
In the documentation it's written : 

> Remark: If you want to transform several 1D arrays at once, use Fftw3.Sig.Array2.dft with ~many:true.
[source](https://github.com/Chris00/fftw-ocaml/blob/ae100823156c088717d598957fffd341abab06ef/src/fftw3.mli#L435)

Is it still a working feature ? I have like 698880 small (32 lengths vectors) 1D transforms to perform, it'd be very great to get this.

Thanks

**Comment by Chris00** [comment]
I haven't been using this lib for a long time.  Any reason to think that something has changed?

**Comment by h2o64** [comment]
Well the parameter simply doesn't exist ^^ (ref: [here](https://github.com/Chris00/fftw-ocaml/blob/ae100823156c088717d598957fffd341abab06ef/src/fftw3.mli#L484))

**Comment by Chris00** [comment]
Sorry for the time taken to fix this.  A new release [will be made](https://github.com/ocaml/opam-repository/pull/12037).  Thanks for reporting!
